repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.8
  hooks: [{id: ruff}]
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks: [{id: black}]
- repo: https://github.com/psf/ruff-pre-commit
  rev: v0.6.8
  hooks: []
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.9
  hooks: [{id: bandit}]
